declare module 'quasar/src/components/dialog/QDialog'
declare module 'quasar/src/components/inner-loading/QInnerLoading'
declare module 'quasar/src/components/spinner/QSpinnerGears'
declare module 'quasar/src/components/btn/QBtn'
declare module 'quasar/src/components/select/QSelect'
